table Orders
	lineageTag: b53fbaea-66b5-49dc-b61a-dd0d74110cd8

	measure 'Total Sales' = SUM(Orders[Sales])
		lineageTag: 68f8ae5b-c3db-4d52-affe-969dcfcb79d2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Profit' = SUM(Orders[Profit])
		lineageTag: 13f5f9bb-a19b-4c9a-a948-db5edb1869f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total order' = DISTINCTCOUNT(Orders[Order ID])
		formatString: 0
		lineageTag: 8a7fe1e1-9be3-4b8c-b0dc-b4090d139b6e

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 4850d286-887f-418b-b229-653d0ba7c19b
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: b7320af6-fa9b-4a5c-8916-b98ae5b57abe
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5102839f-fa50-48dc-a2c6-a9a67d6eaea2
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: dec57366-22d1-47c0-bfea-0bd223910b61
			defaultHierarchy: LocalDateTable_92a8ca67-5757-4109-bb4f-04dc56a5765a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ff61b480-0ac5-4519-a8fc-6c23ae80b5c8
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 6c48c127-ba1c-428b-bc20-058181e6ace8
			defaultHierarchy: LocalDateTable_75bbe750-d1ba-4f3a-9c93-3d48500a982c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: 3f8cd04a-1634-458d-92c4-aa5f0cbf10ff
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: c01c5a8a-2c85-4faa-bcaf-b8942b020c3b
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 2d48ab72-5d02-48e0-a5ec-36873f8b09b8
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: c089a132-1133-41aa-8628-59b59c484c3b
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country/Region
		dataType: string
		lineageTag: ebfc6763-b843-415a-967f-d1fe7bcbf455
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 2a372b07-e00d-44fd-8d5f-25be9727a955
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State/Province
		dataType: string
		lineageTag: 6d4c40b7-9d25-4f56-8d4e-ad4f81ba5404
		summarizeBy: none
		sourceColumn: State/Province

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: ae7f683e-6aa8-4078-8a35-63c4450e513e
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 3bc43df8-2527-45de-9077-03dec25175c7
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 3bc035b0-cd9a-442d-b501-c02bad69532b
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 3d60b628-c901-4c2b-ab32-439b4ca5886b
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 1a9b26fe-9e21-4515-8f5b-e9fcc40063a1
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 023cac8d-c4f1-4fda-a317-663442a3164f
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 0a9bbeb3-ed3d-42b0-992f-780ac44c6ace
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 1a29e3d6-4cf3-4876-81df-fc3b9774816c
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 80d6c793-c6b7-497b-8a47-2a5f8e580fdc
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: dd05e521-2e00-45db-9fff-a4c0ce66c984
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Docker\Downloads\sample_superstore.xls"), null, true),
				    Orders1 = Source{[Name="Orders"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders1, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State/Province", type text}, {"Postal Code", type text}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

